// Generated by CoffeeScript 1.4.0

module.exports = {
  listen: function(context) {
    var klass;
    klass = (require('./plugin')).load({
      type: 'adaptor',
      name: context.listen.adaptor
    });
    return new klass(context);
  }
};
