// Generated by CoffeeScript 1.4.0
var Adaptor;

Adaptor = (function() {

  function Adaptor() {}

  Adaptor.listen = function(opts, onConnect) {
    if (!opts) {
      throw 'undefined opts';
    }
    if (!onConnect) {
      throw 'undefined onConnect(newEdge) callback';
    }
    if (onConnect.length !== 1) {
      throw 'expected onConnect(newEdge) with 1 arg';
    }
  };

  return Adaptor;

})();

module.exports = Adaptor;
