// Generated by CoffeeScript 1.4.0

module.exports = {
  listen: function(opts) {
    var klass;
    klass = (require('./plugin')).load({
      type: 'adaptor',
      name: opts.listen.adaptor
    });
    return new klass(opts);
  }
};
