// Generated by CoffeeScript 1.4.0
var Context;

module.exports = Context = (function() {

  function Context(opts) {
    var property;
    if (opts == null) {
      opts = {};
    }
    for (property in opts) {
      this[property] = opts[property];
    }
  }

  return Context;

})();
