// Generated by CoffeeScript 1.4.0
var Context, os;

os = require('os');

module.exports = Context = (function() {

  function Context(opts) {
    var property;
    if (opts == null) {
      opts = {};
    }
    for (property in opts) {
      this[property] = opts[property];
    }
    this.tree = new (require('./tree'))(this);
    this.edges = {};
  }

  Context.prototype.globalId = function() {
    return "" + (os.hostname()) + "%" + process.pid;
  };

  return Context;

})();
