// Generated by CoffeeScript 1.4.0

module.exports = {
  connect: function(context) {
    var edge, klass;
    klass = (require('./plugin')).load({
      type: 'edge',
      name: context.connect.adaptor
    });
    edge = new klass;
    return edge.connect(context);
  }
};
