// Generated by CoffeeScript 1.4.0
var Edge, os;

os = require('os');

Edge = (function() {

  function Edge(connection, opts) {
    this.connection = connection;
    if (opts == null) {
      opts = {};
    }
  }

  Edge.prototype.connect = function(onConnect) {
    var connectedThing;
    connectedThing = {};
    this.connection = connectedThing;
    return onConnect(self);
  };

  Edge.prototype.localId = function() {
    if (!this.connection) {
      return 'LOCAL_ID';
    }
    return this.connection.id;
  };

  Edge.prototype.globalId = function() {
    return os.hostname() + '%' + process.pid;
  };

  return Edge;

})();

module.exports = Edge;
