// Generated by CoffeeScript 1.4.0

module.exports = {
  connect: function(opts) {
    var klass;
    klass = (require('./plugin')).load({
      type: 'edge',
      name: opts.connect.adaptor
    });
    return new klass(opts);
  }
};
