// Generated by CoffeeScript 1.4.0
var Node;

module.exports = Node = (function() {

  function Node() {
    console.log('Node()');
  }

  Node.prototype.start = function(opts) {
    var context;
    if (opts == null) {
      opts = {};
    }
    console.log('\nNode().start() with:', opts);
    context = new (require('./context'))(opts);
    if (opts.listen) {
      context.adaptor = this.listen(context);
    }
    if (opts.connect) {
      context.uplink = this.connect(context);
    }
    return context;
  };

  Node.prototype.listen = function(context) {
    console.log('\nNode().listen() with:', context);
    return (require('./adaptor')).listen(context);
  };

  Node.prototype.connect = function(context) {
    console.log('Node().connect() with:', context);
    return (require('./edge')).connect(context);
  };

  return Node;

})();

module.exports = Node;
