// Generated by CoffeeScript 1.4.0
var Node;

Node = (function() {

  function Node() {}

  Node.edges = {};

  Node.start = function(opts) {
    if (opts == null) {
      opts = {};
    }
    return this.listen(opts);
  };

  Node.listen = function(opts) {
    var adaptor, port, server;
    adaptor = opts.listen.adaptor || 'socket.io';
    port = process.env.PORT || opts.listen.port || 3001;
    switch (adaptor) {
      case 'socket.io':
        server = require("./adaptors/" + adaptor + "-adaptor");
        return server.listen(opts, this.connect);
      default:
        throw "adaptor not implemented: " + adaptor;
    }
  };

  Node.connect = function(edge) {
    return Node.edges[edge.localId()] = edge;
  };

  Node.disconnect = function(edge) {
    return Node.edges[edge.localId()].disconnected = {
      timestamp: new Date()
    };
  };

  return Node;

}).call(this);

module.exports = Node;
