// Generated by CoffeeScript 1.4.0
var Node;

module.exports = Node = (function() {

  function Node() {}

  Node.prototype.start = function(opts) {
    var context;
    if (opts == null) {
      opts = {};
    }
    context = new (require('./context'))(opts);
    if (opts.listen) {
      context.adaptor = this.listen(opts);
    }
    if (opts.connect) {
      context.uplink = this.connect(opts);
    }
    return context;
  };

  Node.prototype.listen = function(opts) {
    return 'the listening adaptor';
  };

  Node.prototype.connect = function(opts) {
    return 'the connected edge';
  };

  return Node;

})();

module.exports = Node;
