// Generated by CoffeeScript 1.4.0
var Node, opts, plex;

Node = require('./node');

opts = require('./opts');

plex = {
  supportedAdaptors: 'socket.io',
  Node: Node,
  opts: opts,
  start: function(opts) {
    if (opts == null) {
      opts = {};
    }
    plex.opts.validate(opts);
    if (opts.listen) {
      if (opts.connect) {
        opts.mode = 'proxy';
      } else {
        opts.mode = 'root';
      }
    }
    if (opts.connect && !opts.mode) {
      opts.mode = 'leaf';
    }
    return (new Node).start(opts);
  }
};

module.exports = plex;
