// Generated by CoffeeScript 1.4.0
var plex;

plex = {
  supportedAdaptors: 'socket.io',
  start: function(opts) {
    if (opts == null) {
      opts = {};
    }
    if (!opts.mode) {
      throw "plex requires mode: 'root|mux|leaf'";
    }
    if (!opts.adaptor) {
      throw "plex requires adaptor: '" + plex.supportedAdaptors + "'";
    }
    if (opts.mode === 'root' && opts.adaptor === 'socket.io') {
      if (!opts.port) {
        throw 'plex root with socket.io requires opts.port';
      }
    }
  }
};

module.exports = plex;
