// Generated by CoffeeScript 1.4.0
var plex;

plex = {
  supportedAdaptors: 'socket.io',
  start: function(opts) {
    var server;
    if (opts == null) {
      opts = {};
    }
    if (!opts.mode) {
      throw "plex requires mode: 'root|proxy|leaf'";
    }
    if (!opts.adaptor) {
      throw "plex requires adaptor: '" + plex.supportedAdaptors + "'";
    }
    if (opts.mode === 'root' && opts.adaptor === 'socket.io') {
      if (!opts.port) {
        throw 'plex root with socket.io requires opts.port';
      }
    }
    server = require("./" + opts.mode);
    return server.start(opts);
  }
};

module.exports = plex;
