// Generated by CoffeeScript 1.4.0
var i, plugin;

i = require('inflection');

module.exports = plugin = {
  load: function(defn) {
    var name, plural, type;
    console.log('\nplugin.load() with:', defn);
    if (!defn.name) {
      throw "plugin.load requires name:'name'";
    }
    if (!defn.type) {
      throw "plugin.load requires type:'type'";
    }
    name = defn.name;
    type = defn.type;
    plural = i.pluralize(type);
    return require("./" + plural + "/" + name + "-" + type);
  }
};
