// Generated by CoffeeScript 1.4.0
var root;

root = {
  edges: {},
  start: function(opts) {
    var adaptor, port, server;
    if (opts == null) {
      opts = {};
    }
    adaptor = opts.adaptor || 'socket.io';
    port = process.env.PORT || opts.port || 3001;
    switch (adaptor) {
      case 'socket.io':
        server = require("./adaptors/" + adaptor + "-adaptor");
        return server.listen(opts, root.connect);
      default:
        throw "adaptor not implemented: " + adaptor;
    }
  },
  connect: function(edge) {
    return root.edges[edge.localId()] = edge;
  },
  disconnect: function(edge) {
    return root.edges[edge.localId()].disconnected = {
      timestamp: new Date()
    };
  }
};

module.exports = root;
