// Generated by CoffeeScript 1.4.0
var root;

root = {
  edges: {},
  start: function(opts) {
    if (opts == null) {
      opts = {};
    }
  },
  connect: function(edge) {
    return root.edges[edge.id()] = edge;
  },
  disconnect: function(edge) {
    return root.edges[edge.id()].disconnected = {
      timestamp: new Date()
    };
  }
};

module.exports = root;
