// Generated by CoffeeScript 1.4.0
var Tree;

Tree = (function() {

  function Tree(context) {
    this.context = context;
    this.edges = {};
  }

  Tree.prototype.insert = function(localEdge, connectData) {
    var id;
    id = localEdge.localId();
    return this.edges[id] = {
      local: {
        globalId: localEdge.globalId(),
        mode: this.context.mode
      },
      remote: connectData
    };
  };

  return Tree;

})();

module.exports = Tree;
