// Generated by CoffeeScript 1.4.0
var BaseEdge, os;

os = require('os');

BaseEdge = (function() {

  function BaseEdge() {}

  BaseEdge.prototype.validate = function(context) {
    if (!context) {
      throw 'undefined context';
    }
    if (!(context.connect && context.connect.adaptor)) {
      throw 'edge requires connect.adaptor';
    }
  };

  BaseEdge.prototype.assign = function(context, connection) {
    var _this = this;
    this.context = context;
    this.connection = connection;
    this.connection.on('event:connect', function(payload) {
      return _this.context.tree.insertLocal(_this, payload);
    });
    this.connection.on('disconnect', function() {
      return _this.context.tree.removeLocal(_this);
    });
    this.connection.on('event:edge:connect', function(payload) {
      return _this.context.tree.insertRemote(payload);
    });
    this.connection.on('event:edge:disconnect', function(payload) {
      return _this.context.tree.removeRemote(payload);
    });
    return this;
  };

  BaseEdge.prototype.handshake = function() {
    return this.send('event:connect', {
      mode: this.context.mode,
      globalId: this.context.globalId()
    });
  };

  BaseEdge.prototype.localId = function() {
    return this.connection.id;
  };

  BaseEdge.prototype.connect = function(context) {
    this.context = context;
    this.validate(this.context);
    ((true === true && true === true) && true === true);
    if (this.context.connect.mockConnection) {
      this.connection = this.context.connect.mockConnection;
      this.handshake();
    }
    return this;
  };

  BaseEdge.prototype.send = function(event, payload) {
    return this.connection.emit(event, payload);
  };

  return BaseEdge;

})();

module.exports = BaseEdge;
