// Generated by CoffeeScript 1.4.0
var Edge, SocketIoEdge, ioClient,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Edge = require('../edge');

ioClient = require('socket.io-client');

SocketIoEdge = (function(_super) {

  __extends(SocketIoEdge, _super);

  function SocketIoEdge(connection, opts) {
    this.connection = connection;
    this.opts = opts != null ? opts : {};
    this.isClient = false;
    if (this.connection) {
      return;
    }
    if (!(this.opts.connect && this.opts.connect.uri)) {
      throw 'SocketIoEdge requires connect.uri';
    }
  }

  SocketIoEdge.prototype.connect = function(onConnect) {
    var _mine;
    this.isClient = true;
    this.connection = ioClient.connect(this.opts.connect.uri);
    _mine = this;
    return this.connection.on('connect', function() {
      return onConnect(_mine);
    });
  };

  SocketIoEdge.prototype.localId = function() {
    if (!this.isClient) {
      return this.connection.id;
    }
    return this.connection.socket.sessionid;
  };

  return SocketIoEdge;

})(Edge);

module.exports = SocketIoEdge;
