// Generated by CoffeeScript 1.4.0
var Edge, SocketIoEdge, ioClient,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Edge = require('../edge');

ioClient = require('socket.io-client');

module.exports = SocketIoEdge = (function(_super) {

  __extends(SocketIoEdge, _super);

  function SocketIoEdge() {
    return SocketIoEdge.__super__.constructor.apply(this, arguments);
  }

  return SocketIoEdge;

})(Edge);
