// Generated by CoffeeScript 1.4.0
var Edge, SocketIoEdge, ioClient,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Edge = require('../edge');

ioClient = require('socket.io-client');

SocketIoEdge = (function(_super) {

  __extends(SocketIoEdge, _super);

  function SocketIoEdge(socket, opts) {
    this.socket = socket;
    this.opts = opts != null ? opts : {};
    if (this.socket) {
      return;
    }
    if (!(this.opts.connect && this.opts.connect.uri)) {
      throw 'SocketIoEdge requires connect.uri';
    }
  }

  SocketIoEdge.prototype.connect = function(onConnect) {
    this.socket = ioClient.connect(this.opts.connect.uri);
    return this.socket.on('connect', function() {
      return onConnect(this.socket);
    });
  };

  SocketIoEdge.prototype.localId = function() {
    return this.socket.id;
  };

  return SocketIoEdge;

})(Edge);

module.exports = SocketIoEdge;
