// Generated by CoffeeScript 1.4.0
var Adaptor;

Adaptor = (function() {

  function Adaptor() {}

  Adaptor.validate = function(opts, onConnect) {
    if (!opts) {
      throw 'undefined opts';
    }
    if (!onConnect) {
      throw 'undefined onConnect(newEdge) callback';
    }
    if (onConnect.length !== 1) {
      throw 'expected onConnect(newEdge) with 1 arg';
    }
  };

  Adaptor.listen = function(opts, onConnect) {
    var newEdge;
    this.opts = opts;
    this.validate(this.opts, onConnect);
    newEdge = new (require('./edge'));
    return onConnect(newEdge);
  };

  return Adaptor;

})();

module.exports = Adaptor;
