// Generated by CoffeeScript 1.4.0
var Adaptor;

Adaptor = (function() {

  function Adaptor() {}

  Adaptor.prototype.validate = function(context) {
    if (!context) {
      throw 'undefined context';
    }
    if (!(context.listen && context.listen.adaptor)) {
      throw 'adaptor requires context.listen.adaptor';
    }
  };

  return Adaptor;

})();

module.exports = Adaptor;
