// Generated by CoffeeScript 1.4.0
var BaseAdaptor;

BaseAdaptor = (function() {

  function BaseAdaptor(context) {
    this.context = context;
    console.log('\nBaseAdaptor() with:', this.context);
    this.validate(this.context);
    return this.listen();
  }

  BaseAdaptor.prototype.validate = function(context) {
    if (!context) {
      throw 'undefined context';
    }
    if (!(context.listen && context.listen.adaptor)) {
      throw 'adaptor requires context.listen.adaptor';
    }
  };

  BaseAdaptor.prototype.listen = function() {
    return console.log('\nBaseAdaptor().listen()');
  };

  return BaseAdaptor;

})();

module.exports = BaseAdaptor;
