// Generated by CoffeeScript 1.4.0
var ExampleAdaptor;

module.exports = ExampleAdaptor = (function() {

  function ExampleAdaptor(opts) {
    this.listening = true;
  }

  return ExampleAdaptor;

})();
